### ISSUE TITLE
inconsistency between the masked adam description in paper and the code implementation

### ISSUE THREAD

**Issue by abstrcode** [jason718/semi-sup#2]
It seems there is no masked adam in the code. However, it claimed masked adam is helpful.

**Comment by jason718** [comment]
https://github.com/jason718/semi-sup/blob/f9f9b4ecf3609dbde759203fa653dee9f2368a6e/main.py#L284

**Comment by wwwyn** [comment]
Thanks for your reply. I noticed this function. It seems to me the adam update is the same as the original adam update and no mask here.

**Comment by jason718** [comment]
no, we use per-example parameters in Adam:
https://github.com/jason718/semi-sup/blob/f9f9b4ecf3609dbde759203fa653dee9f2368a6e/main.py#L59, and then only update the ones that in current mini-batch indexed by `batch_ids`. In contrast, vanilla Adam use the same set of parameters for all examples.
